# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "tailwind-landing-pages-theme"
license = "MIT"
licenselink = "https://gitlab.com/fuww/tailwind-landing-pages-theme/-/blob/main/LICENSE"
description = "starter theme featuring Tailwind CSS"
homepage = "https://gitlab.com/fuww/tailwind-landing-pages-theme"
tags = ["blog", "seo", "starter"]
features = ["structured data","shortcodes","partials","seo","schema"]

[author]
    name = "Joost van der Laan"
    homepage = "https://gitlab.com/joostl"
